"""add affiliate models

Revision ID: 8fb1af0be240
Revises: d4e5f6g7h8i9
Create Date: 2026-05-19 23:16:47.670350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fb1af0be240'
down_revision = 'd4e5f6g7h8i9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type if it doesn't exist
    job_status = postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='jobstatus')
    job_status.create(op.get_bind(), checkfirst=True)

    op.create_table('affiliate_post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shopee_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('price', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='jobstatus', create_type=False), nullable=False),
    sa.Column('sagemaker_output_s3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_click',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['affiliate_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_index(op.f('ix_post_user_id'), table_name='post')
    # op.drop_table('post')
    # op.drop_index(op.f('ix_affiliateclick_post_id'), table_name='affiliateclick')
    # op.drop_table('affiliateclick')
    # op.drop_table('like')
    # op.alter_column('avatar_job', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'pending'::character varying"))
    # op.alter_column('tryon_job', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'pending'::character varying"))
    # op.alter_column('video_tryon_job', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_tryon_job', 'status',
               existing_type=sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('tryon_job', 'status',
               existing_type=sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('avatar_job', 'status',
               existing_type=sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table('like',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('like_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('like_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('like_pkey'))
    )
    op.create_table('affiliateclick',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('referrer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('affiliateclick_buyer_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('affiliateclick_post_id_fkey')),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], name=op.f('affiliateclick_referrer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('affiliateclick_pkey'))
    )
    op.create_index(op.f('ix_affiliateclick_post_id'), 'affiliateclick', ['post_id'], unique=False)
    op.create_table('post',
    sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('garment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garment.id'], name=op.f('post_garment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('post_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_pkey'))
    )
    op.create_index(op.f('ix_post_user_id'), 'post', ['user_id'], unique=False)
    op.drop_table('affiliate_click')
    op.drop_table('affiliate_post')
    # ### end Alembic commands ###
