"""Add multi-worker fields to TryOnJob

Revision ID: 904b271fa044
Revises: 25ab022a8e74
Create Date: 2026-05-19 22:15:05.986814

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '904b271fa044'
down_revision = '25ab022a8e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tryon_job', sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('tryon_job', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tryon_job', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('tryon_job', sa.Column('engine_preference', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE tryon_job SET retry_count = 0 WHERE retry_count IS NULL")
    op.execute("UPDATE tryon_job SET engine_preference = 'auto' WHERE engine_preference IS NULL")
    
    # Now make retry_count NOT NULL
    op.alter_column('tryon_job', 'retry_count', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tryon_job', 'engine_preference')
    op.drop_column('tryon_job', 'retry_count')
    op.drop_column('tryon_job', 'claimed_at')
    op.drop_column('tryon_job', 'worker_id')
    # ### end Alembic commands ###
