"""Sync models status enum and tiki_link

Revision ID: a8f15e654c94
Revises: ab6257a705ff
Create Date: 2026-05-20 04:01:09.915074

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8f15e654c94'
down_revision = 'ab6257a705ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affiliate_post', 'tiki_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # We skip complex enum migrations for now to avoid default value cast issues
    # They are not strictly needed for the current fix.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affiliate_post', 'tiki_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
