"""Add is_active to AffiliatePost

Revision ID: ab6257a705ff
Revises: 65889bb49d7a
Create Date: 2026-05-20 03:59:53.510581

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab6257a705ff'
down_revision = '65889bb49d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # We add is_active column to affiliate_post
    op.add_column('affiliate_post', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_post', 'is_active')
    # ### end Alembic commands ###
