"""Convert clip_embedding from JSON to vector(768)

Revision ID: b2c3d4e5f6g7
Revises: 1a31ce608336
Create Date: 2026-05-14 10:00:00.000000

"""
from alembic import op

revision = "b2c3d4e5f6g7"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # Drop existing JSON data (embeddings will be regenerated by CLIP endpoint)
    op.execute("UPDATE garment SET clip_embedding = NULL")
    # Change column type from JSON to vector(768)
    op.execute(
        "ALTER TABLE garment "
        "ALTER COLUMN clip_embedding TYPE vector(768) "
        "USING NULL"
    )


def downgrade():
    op.execute(
        "ALTER TABLE garment "
        "ALTER COLUMN clip_embedding TYPE JSON "
        "USING NULL"
    )
